base_url = "https://aterenin.github.io/academic-workshop"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme, which is [designed to last](https://jeffhuang.com/designed_to_last/)."
title = {tagline = "Presenting the", title = "2026 Nordic-RSE Conference", subtitles = ["Troms√∏"]}
banner = {extension = "svg", size = "fixed", fade = true}
buttons = [{name = "Website", url = "https://nordic-rse.org/nrse2026"}, {name="GitHub", url="http://github.com/nordic-rse/nrse2026"}]
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
header_pages = [{name = "Home", url = "/#home"},{name = "Design", url = "/#design"}]
button_shortcuts = [{variable = "video", name = "Video"}]
